### ISSUE TITLE
Supporting NFT by Puzzle Market

### ISSUE THREAD

**Issue by vlzhr** [automainint/clef#1]
To have NFT-melody supported by PuzzleMarket.org just replace this line of code

`let issue   = Issue(name.take(16), "Clef song.", 1, 0, false)`

Issue NFT directly with PuzzleMarket SDK [LINK](https://gist.github.com/vlzhr/3ea1a31e919e75abd0e9d5948cbc0e14)

**Comment by vlzhr** [comment]
PS. Ask to whitelist Address of your dApp beforehand

**Comment by automainint** [comment]
@vlzhr Thanks!
